// <auto-generated by="the Blazor I18n Text compiler" />
namespace MudBlazorInputFile.I18nText.App
{
    public partial class Localize : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Source Code"</summary>
        public string Source_Code;

        /// <summary>"Material Designed &quot;input type=file&quot; with MudBlazor"</summary>
        public string Title;
    }
}
